apiVersion: v1
kind: Service
metadata:
  name: smog-frontend-service
  namespace: smog-prediction
  labels:
    app: smog-frontend
spec:
  type: LoadBalancer
  selector:
    app: smog-frontend
  ports:
    - port: 80
      targetPort: 80
